apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: hello-server-myapp1
  name: hello-server-myapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      run: hello-server-myapp1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: hello-server-myapp1
    spec:
      containers:
      - image: docker.pkg.github.com/ichtestemalwieder/myapp:latest
        name: hello-server-myapp1
        ports:
        - containerPort: 8080
        resources: {}
      imagePullSecrets:
      - name: github

status: {}
