name: Node CI

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      if: github.ref == 'refs/heads/master' #Workaround, as no conditional jobs or dependant workflows are supported. Prevent execution for untrusted Pull-Requests.
      run: |
        npm install
        npm run build --if-present
    - name: Build the Docker image
      if: github.ref == 'refs/heads/master' #Workaround
      run:  docker build . --file Dockerfile --tag ichtestemalwieder/myapp:${{github.sha}} --tag ichtestemalwieder/myapp:latest #TODO name by branch
    - name: Docker Login & Push
      if: github.ref == 'refs/heads/master' #Workaround
      run: |
         docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
         docker push ichtestemalwieder/myapp
    - name: Github Docker Repo Login & Push
      if: github.ref == 'refs/heads/master' #Workaround
      run: |
         docker login docker.pkg.github.com --username=${{ secrets.DOCKER_USERNAME }} --password=${{secrets.REGISTRYPWD}}
         docker tag myapp docker.pkg.github.com/ichtestemalwieder/hello-world/myapp:latest
         docker push docker.pkg.github.com/ichtestemalwieder/hello-world/myapp:latest
         docker push ichtestemalwieder/myapp
                  
