name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: npm install, build, and test
      run: |
        pwd
        ls -lisa 
        npm install
        npm run build --if-present
        pwd
        ls -lisa
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ichtestemalwieder/ichtestemalwieder1:$(date +%s)
    - name: Docker Login & Push
      run: |
         docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
         docker push ichtestemalwieder/ichtestemalwieder
      
